// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpIdCj9FmkALrrABgDv4K_dvfJUzvOuOg',
    appId: '1:1017198753025:web:6c7f7fa055ee136ddf9700',
    messagingSenderId: '1017198753025',
    projectId: 'splitsaathi-adc13',
    authDomain: 'splitsaathi-adc13.firebaseapp.com',
    storageBucket: 'splitsaathi-adc13.firebasestorage.app',
    measurementId: 'G-BHHC2PC74P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCu3-jAJ4fDJUB-zygo3U-2TWG8nQlg624',
    appId: '1:1017198753025:android:bbafa70f577b2f31df9700',
    messagingSenderId: '1017198753025',
    projectId: 'splitsaathi-adc13',
    storageBucket: 'splitsaathi-adc13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMpG7chtLiPm6InlXsuPUKPmgIHKqiQYo',
    appId: '1:1017198753025:ios:c612833eb73db018df9700',
    messagingSenderId: '1017198753025',
    projectId: 'splitsaathi-adc13',
    storageBucket: 'splitsaathi-adc13.firebasestorage.app',
    iosBundleId: 'com.example.splitSaathi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMpG7chtLiPm6InlXsuPUKPmgIHKqiQYo',
    appId: '1:1017198753025:ios:c612833eb73db018df9700',
    messagingSenderId: '1017198753025',
    projectId: 'splitsaathi-adc13',
    storageBucket: 'splitsaathi-adc13.firebasestorage.app',
    iosBundleId: 'com.example.splitSaathi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpIdCj9FmkALrrABgDv4K_dvfJUzvOuOg',
    appId: '1:1017198753025:web:d874e4b07e2fd607df9700',
    messagingSenderId: '1017198753025',
    projectId: 'splitsaathi-adc13',
    authDomain: 'splitsaathi-adc13.firebaseapp.com',
    storageBucket: 'splitsaathi-adc13.firebasestorage.app',
    measurementId: 'G-D4JH7L5D8Q',
  );
}
